# Generated by Django 2.2 on 2023-10-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('salary', models.FloatField(default=0.0, verbose_name='Salary')),
                ('ot_rate', models.IntegerField(default=0, verbose_name='Ot Rate')),
                ('allowance', models.IntegerField(default=0, verbose_name='Allowance')),
                ('deduction', models.IntegerField(default=0, verbose_name='Deduction')),
                ('tax', models.FloatField(default=0.0, verbose_name='Tax')),
                ('bonus', models.FloatField(default=0.0, verbose_name='Bonus')),
                ('insurance', models.CharField(choices=[('health', 'Health Insurance'), ('life', 'Life Insurance'), ('auto', 'Auto Insurance'), ('property', 'Property Insurance'), ('other', 'Other')], default='health', max_length=10, verbose_name='Insurance Type')),
            ],
        ),
    ]
