# Generated by Django 2.2 on 2023-11-01 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tags', '0001_initial'),
        ('hr_jobs', '0003_jobmodel_tags'),
        ('hr_employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_jobs.JobModel', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='tags',
            field=models.ManyToManyField(to='hr_tags.EmployeeTagModel'),
        ),
    ]
