# Generated by Django 2.2 on 2023-10-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('clock_in', models.TimeField(verbose_name='Clock In')),
                ('clock_out', models.TimeField(verbose_name='Clock Out')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hours Worked')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
            ],
        ),
    ]
