# Generated by Django 2.2 on 2023-11-01 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employees', '0002_auto_20231101_0911'),
        ('hr_tags', '0001_initial'),
        ('hr_contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_employees.EmployeeModel', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='tags',
            field=models.ManyToManyField(to='hr_tags.ContractTagModel', verbose_name='Tags'),
        ),
    ]
