# Generated by Django 2.2 on 2023-11-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_tags', '0001_initial'),
        ('hr_jobs', '0002_jobmodel_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='tags',
            field=models.ManyToManyField(to='hr_tags.JobTagModel'),
        ),
    ]
