# Generated by Django 2.2 on 2023-10-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Receipt Number'),
        ),
    ]
